#!/usr/bin/python3
print("              ")
print(" Availability ")
print("              ")
This the types of hours that exist for doctors workdays 
Availability= {'Ofcice hours' : '08:00 A.M - 3 P.M',
               'Emmergency hours' : '3 PM - 10 PM',
               'Non possible hours'  : '11 P.M - 7 A.M',
                }

for keys, values in sorted(Availability.items()):
    print("{}: {}".format(keys, values))
